spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: database

security:
  jwt:
    token:
      secret-key:
        access: secret-key
        refresh: secret-key
      expired-length: 3600000

oauth:
  google:
    client-id: client-id
    client-secret: client-secret
    redirect-uri: redirect-uri
    grant-type: grant-type
    post-url: post-url
    get-url: get-url
    redirect-fillkie: fillkie-uri

logging:
  level:
    root: info

server:
  port: 8080
  servlet:
    context-path: /app