name: push-to-mirror

on: [push]

jobs:
  push-to-mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: ${{ secrets.GITLAB_REPO_URL }}
      env:
        GITLAB_HOSTNAME: ${{ secrets.GITLAB_HOSTNAME }}
        GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
